version: "3"
services:
    web:
        build: OnBoarding/
        ports:
            - "8082:5001"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux:2017-latest"
        environment:
            SA_PASSWORD: "Test@123"
            ACCEPT_EULA: "Y"
        ports: 
            - "1442:1433"
